apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ixuzdz34f-go
  janus-idp.io/tekton: ixuzdz34f-go
  backstage.io/kubernetes-id: ixuzdz34f-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ixuzdz34f-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
